<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BehanceProjectsSeeder extends Seeder
{
    public function run(): void
    {
        // Total: 122 projects
        // Generated: 2026-04-30 20:53:12

        $now = now();

        $data = [
            [
                'user_id'        => 0,
                'title'          => 'Okko',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/96d382247611261.69dfaed815cb0.png',
                'slug'           => 'okko-17fbd641',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => '2024 LETTERPRESS CALENDAR',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/4a69ba240988053.694b0ad4814e0.jpg',
                'slug'           => '2024-letterpress-calendar-62aa0c4c',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Countryside ( March 1 )',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/edd20d245350399.69ab90f38209a.jpg',
                'slug'           => 'countryside--march-1-0d8a38a5',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'NH올원뱅크 ICON DESIGN',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/71e228247544779.69dda797a59e1.jpg',
                'slug'           => 'nh-icon-design-267f4f2d',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'FROZEN COLORS OF WINTER – Germany',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/ca32fd188728551.65a0355e4fcbf.jpg',
                'slug'           => 'frozen-colors-of-winter--germany-342eed6f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Aviation Website | UX UI',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/258c34247542211.69dd91dd1bce6.jpg',
                'slug'           => 'aviation-website--ux-ui-acb26346',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Los Gigantes',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/b0db68197894189.663898b310547.jpg',
                'slug'           => 'los-gigantes-7b5144ce',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'MASCOTFOLIO Vol.03 26',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/0c4262247697907.69e0bcf149dc1.png',
                'slug'           => 'mascotfolio-vol03-26-1d5f43d5',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Just My Type',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/45b5bd179194581.654ce53a5dcde.jpg',
                'slug'           => 'just-my-type-0a7be245',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Institute of Health',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/ba9579247061597.69d2daeb3ecbc.png',
                'slug'           => 'institute-of-health-8ab26221',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Concept website for an iconic music brand',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/2039c5208574817.69cbaca29bb0e.png',
                'slug'           => 'concept-website-for-an-iconic-music-brand-1c605f1e',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'R\\AW skincare \\ Brand & Packaging Identity',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/49be31247329451.69db68b64b3a0.png',
                'slug'           => 'raw-skincare--brand--packaging-identity-48993b15',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'HONOR MAGIC VS2 WALLPAPERS',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d4b8d1222784831.68f8d83ff3f8d.jpg',
                'slug'           => 'honor-magic-vs2-wallpapers-91bee949',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Jeonju University Branding 2025',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/6c3b1b233772067.68b65c1a615c5.jpg',
                'slug'           => 'jeonju-university-branding-2025-4bd1c7e5',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Some of my 3-frames comics',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/79635935954027.5a6a29beadaec.jpg',
                'slug'           => 'some-of-my-3frames-comics-4734541d',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'AI Robotics Website Design & Webflow | Emancro',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d2e3f8242251083.69c3fe0aa041c.jpg',
                'slug'           => 'ai-robotics-website-design--webflow--emancro-91f597f6',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Sossusvlei. - Deserto del Namib',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/3783f9244549939.6999fd40aa142.jpg',
                'slug'           => 'sossusvlei--deserto-del-namib-20c2195e',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Faces of January 2026',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/7985be242696147.6972162b31330.png',
                'slug'           => 'faces-of-january-2026-1a21e122',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Vintage & Sporty T-Shirt Lettering',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/bb487e247629315.69df61a27d8de.jpg',
                'slug'           => 'vintage--sporty-tshirt-lettering-1721bef7',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'TOP@15',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/b05c1b247072045.69d342b23aa52.jpg',
                'slug'           => 'top15-517c1eaa',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'moment of stillness',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/14ab54241770189.695f4801dfae0.jpg',
                'slug'           => 'moment-of-stillness-c17c920f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Animal characters',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e32d88243140649.697c2daf8dc88.jpeg',
                'slug'           => 'animal-characters-e044d02c',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Pigmy owl',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/952b75247411791.69da434474e8d.jpg',
                'slug'           => 'pigmy-owl-410a4120',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Bitsy Variable Font',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/09682e246792735.69cd48e87f3df.png',
                'slug'           => 'bitsy-variable-font-76bc382f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'BaoBao｜餐具品牌设计',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5bc22a248377789.69f05bdba0654.jpg',
                'slug'           => 'baobao-12d3bd99',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Kabushima Shrine',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/3d45b4247888761.69e5894423bf2.jpg',
                'slug'           => 'kabushima-shrine-d7e2eb60',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'illustrandom #01',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/789bd3181695221.65a7c05f7424e.png',
                'slug'           => 'illustrandom-01-34aad9c4',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Rheinalt',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/221316232967439.68a7421647c23.jpg',
                'slug'           => 'rheinalt-15cc961c',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'PACKAGE DESIGN FOR ANKA BAGS BRAND',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/96fb5c233641539.68b36fc72f5cf.jpg',
                'slug'           => 'package-design-for-anka-bags-brand-620bc542',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'AMG GTC',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/c412d3247861593.69e4d052b839d.jpg',
                'slug'           => 'amg-gtc-f43abad6',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'New CUPRA Яaval VZ',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/cc3682247289457.69d77e8c5431f.jpg',
                'slug'           => 'new-cupra-aval-vz-05c4ae2d',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Jomo’s adventures',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/76c769206482429.66cd811d535cd.jpg',
                'slug'           => 'jomos-adventures-b3abe0f8',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'SWEET HOLIDAYS : Christmas in LOTTE TOWN',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/451d6b242680559.6971db8383cae.jpg',
                'slug'           => 'sweet-holidays--christmas-in-lotte-town-b6f9651d',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'SERIE ANIMADA M.P / MICAH PARSON ANIMATED SERIES',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/f5dc84234613593.68c72c885412b.jpg',
                'slug'           => 'serie-animada-mp--micah-parson-animated-series-ca17cf07',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'ROYALS',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5ad54a175716259.64b83470cdf6f.jpg',
                'slug'           => 'royals-cc85b515',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Rolling Out The Purple Carpet for Women in Film & TV',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d6ba13220161997.67be3125252a1.jpg',
                'slug'           => 'rolling-out-the-purple-carpet-for-women-in-film--tv-0849b36b',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Fantasy Illustrations 2024',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/7135d3201548549.67b845bdd66dd.jpg',
                'slug'           => 'fantasy-illustrations-2024-a75bf3ad',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'cloud architecture',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/363603241586077.695bd5a5e8e6b.jpg',
                'slug'           => 'cloud-architecture-144de414',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Still Talkin\' Nashville Honky Tonkin\'',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/4fbde0245672741.69b2a05a5dfe3.jpg',
                'slug'           => 'still-talkin-nashville-honky-tonkin-ebbceb7b',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Vienieto',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/bc6ac3243078841.697bc24a2cc07.jpg',
                'slug'           => 'vienieto-55c60e5b',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => '水天一色 · 2026 IV',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/4db76f245901255.69dceacdefb25.jpeg',
                'slug'           => '2026-iv-f4c25c4c',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'AgroPulse | AI Automation | Orbix Studio | Illustration',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/f60334243842135.698a45d8a8e72.jpg',
                'slug'           => 'agropulse--ai-automation--orbix-studio--illustration-3f79f216',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'YOUR FRIENDLY NEIGHBORHOOD SPIDER-MAN Posters',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/2598b3220242573.67bf676f284ff.jpg',
                'slug'           => 'your-friendly-neighborhood-spiderman-posters-2b2d0482',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'selection of illustrations 2023-2025',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/67afe3177101073.65413083e8237.jpg',
                'slug'           => 'selection-of-illustrations-20232025-1ea471ea',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Grotesque Silhouettes',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d09d97248121843.69ea2338ef540.png',
                'slug'           => 'grotesque-silhouettes-eaa1d91a',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Fintech Product Design – Crypto App, Web UI & Branding',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/b93d6c243705045.6987152d12bb4.png',
                'slug'           => 'fintech-product-design--crypto-app-web-ui--branding-6857ee5f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Visual Identity System for FocalSkin 护肤科学品牌',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/07e220247633311.69df6f556e0f4.jpg',
                'slug'           => 'visual-identity-system-for-focalskin-98d0eb8a',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Clarimol — AI-Driven Drug Discovery Platform',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/6553d2247174839.69d529153e95b.png',
                'slug'           => 'clarimol--aidriven-drug-discovery-platform-502f5e45',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'WELCOME TO MY WORLD',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/62b70a188715837.65a010e46b564.jpg',
                'slug'           => 'welcome-to-my-world-93794fde',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Branding Mimu Vet',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/449e0b233324787.68ad96af17ef8.jpg',
                'slug'           => 'branding-mimu-vet-9ac7d3d9',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Free Illustration Vol.1',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e2e3ce186342897.6577497a7018e.gif',
                'slug'           => 'free-illustration-vol1-6e5bc8f0',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Sensibilities womenswear brand identity design',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/6238b9215003855.67628ebdcea6d.jpg',
                'slug'           => 'sensibilities-womenswear-brand-identity-design-bbc470f0',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'My Garden',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5e4b50248400111.69f0d576a0245.jpg',
                'slug'           => 'my-garden-48dba606',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Runo - AI-powered Fintech Platform UX/UI Design',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/064d5c247987115.69e9364742ab4.png',
                'slug'           => 'runo--aipowered-fintech-platform-uxui-design-d7c2f2d3',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Logofolio 2021-25',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/81729c246718107.69cac4cad37e1.jpg',
                'slug'           => 'logofolio-202125-edfbf3fd',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'WebApp UI/UX Design, Mobile App Design & Brand Identity',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/4d7967247623775.69df4777685de.jpg',
                'slug'           => 'webapp-uiux-design-mobile-app-design--brand-identity-b330ae43',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => '10 AM – Where Happiness Still Lives',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/fea432246691605.69ca60f002cf3.jpg',
                'slug'           => '10-am--where-happiness-still-lives-ea714d32',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Stargate Finance — Branding / Part 1',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/ce2573230511570.6892ea40e4006.jpg',
                'slug'           => 'stargate-finance--branding--part-1-e7a1c99c',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Emily lines camera UV Remap',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/53bd9f247971059.69e73ceb87882.jpg',
                'slug'           => 'emily-lines-camera-uv-remap-edce29e9',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'VidGen - AI Video Creation & UX UI Design Dashboard',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/48513f222950417.67efd87c4c725.png',
                'slug'           => 'vidgen--ai-video-creation--ux-ui-design-dashboard-f3e2ef6d',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Friday\'s Here',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/a101a6247656135.69dfc62e0e193.png',
                'slug'           => 'fridays-here-69e084a3',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'VIKING KRAN',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/2e0b1c247227619.69e72a4c7543a.jpg',
                'slug'           => 'viking-kran-93180d44',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Strike Trade. UX/UI for web application',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/3bd536245976845.69b98879ed4df.png',
                'slug'           => 'strike-trade-uxui-for-web-application-c71ee72b',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Various Illustrations 2023 — 2024.',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/0e81ee189936025.65b2ab2085778.jpg',
                'slug'           => 'various-illustrations-2023--2024-8b85ed23',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Delaware',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d6bcbc247645087.69df9baa65b37.jpg',
                'slug'           => 'delaware-b081a8c4',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Chile, from Atacama to Patagonia',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/57e170187924485.6593e107cdbcc.jpg',
                'slug'           => 'chile-from-atacama-to-patagonia-50d9d15f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'NestEgg: App & Dashboard Design',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/cb3e70246825297.69ccfb307d79b.png',
                'slug'           => 'nestegg-app--dashboard-design-cb0f450b',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'V9 Tales of Business Negotiation',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d55a74247677749.69e04cdc2ad2d.jpg',
                'slug'           => 'v9-tales-of-business-negotiation-182b20f0',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Izaak Reich – visual identity',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/19c26c233541029.68b1633981e09.jpg',
                'slug'           => 'izaak-reich--visual-identity-358ce170',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Hooman Pet Club©',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/f565b6231723613.68a603e57d01c.jpg',
                'slug'           => 'hooman-pet-club-ad24a665',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Citywalk Impressions',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/fdc2d9242231035.6968b69050d94.jpg',
                'slug'           => 'citywalk-impressions-93636389',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Etape 2030 de la transition écologique',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/44daf8189387909.65aa822a30fdf.jpg',
                'slug'           => 'etape-2030-de-la-transition-cologique-fdc63234',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => '25/26 ballet',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/d053e8226943577.683729caba02e.png',
                'slug'           => '2526-ballet-49c45555',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'The Last Guardian Angel 4 Page Epilogue',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d205aa240782727.6945bfd60f20e.jpg',
                'slug'           => 'the-last-guardian-angel-4-page-epilogue-c196a690',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => '\'Handmade\' Greyscalegorilla Plus',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/a3c7b3187263329.65847ba22395a.jpg',
                'slug'           => 'handmade-greyscalegorilla-plus-aefc1b82',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'CNK | Clock and kraft | Branding',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d0870b232870795.68a7b1f5bb447.png',
                'slug'           => 'cnk--clock-and-kraft--branding-d6d84ebd',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Fell On Black Days (2024)',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e6c6b0210096107.670b836cb8255.jpg',
                'slug'           => 'fell-on-black-days-2024-59b9666a',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Illustration for Easy Car / 2022悠遊卡股份有限公司永續報告書插圖',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/fd4d95191120603.65c5d4c37d693.jpg',
                'slug'           => 'illustration-for-easy-car--2022-ce7cead7',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Pizzeria Alberico',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/de1d6e187955675.659445602ae0f.png',
                'slug'           => 'pizzeria-alberico-c0652070',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'New Blues Typeface',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/71b7b9247995437.69e79bd19267b.gif',
                'slug'           => 'new-blues-typeface-353c5ba9',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Arabic Logos&Marks/2026©',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e35416247563515.69de120e739a2.png',
                'slug'           => 'arabic-logosmarks2026-b5b9af5a',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Digital Art: Famous Writers Illustration Set',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/996d49212577871.6737341bcc700.png',
                'slug'           => 'digital-art-famous-writers-illustration-set-223c2415',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Gynecology Department',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5e4929152625055.632173054b496.jpg',
                'slug'           => 'gynecology-department-082ac1a9',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Svelte Collective - Brand Identity Redesign',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e5cc33232912365.68a5b5bf09fc2.png',
                'slug'           => 'svelte-collective--brand-identity-redesign-8d4b1501',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Character Design + Comic Pages Commission',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/3e92fc248152551.69ee9eaf28749.png',
                'slug'           => 'character-design--comic-pages-commission-57012e18',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'wanderer',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/7ba927248097067.69e9b56833794.jpg',
                'slug'           => 'wanderer-87170d5e',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Corktown',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/fe9415188127601.6596e0c0b2207.jpg',
                'slug'           => 'corktown-6aa0a52b',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'AMBER ICE — Germany',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/81f7c7246960209.69cfd1b866c7e.jpg',
                'slug'           => 'amber-ice--germany-966b99a3',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Lagrove Branding',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/825dbb232644053.68a06be9be56d.jpg',
                'slug'           => 'lagrove-branding-73a4f8fe',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Geovea - AI Assistant UX UI Design',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/9d2c34223317987.67f697c30939e.png',
                'slug'           => 'geovea--ai-assistant-ux-ui-design-b116afe5',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'NATURAL ICE CREAM',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/61154d247232949.69d6528ccd27e.jpg',
                'slug'           => 'natural-ice-cream-11010445',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'NutriRecipes Food — Mobile App UX UI Design',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/da04da247353771.69d8d0e0489d8.png',
                'slug'           => 'nutrirecipes-food--mobile-app-ux-ui-design-8de9f296',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'SIGNAL',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/05f044248284571.69ee427404779.jpg',
                'slug'           => 'signal-70573de0',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'SOI® | UX/UI Design',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/18a790247421615.69df8e27e8e3a.jpg',
                'slug'           => 'soi--uxui-design-dbb9ac98',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'DocVisit | Doctor Appointment App | UI/UX Design',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/bb7ee0246957745.69cfc45da2b77.png',
                'slug'           => 'docvisit--doctor-appointment-app--uiux-design-1be6c06f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'OMG!Space – IT Branding & Corporate identity',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5e0c39229035287.68ad707dee8e1.png',
                'slug'           => 'omgspace--it-branding--corporate-identity-ac02aae3',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Mini Cooper SFO',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/0fb3d4247731929.69e14902c3a46.jpg',
                'slug'           => 'mini-cooper-sfo-a211be1f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Trémoille – men\'s perfume landing page | UX/UI',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/be4187247248467.69d68affd2a92.png',
                'slug'           => 'trmoille--mens-perfume-landing-page--uxui-d156ab55',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Hilton',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/4c5a06227397577.68420686e0270.jpg',
                'slug'           => 'hilton-7d1831db',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Namib | Where Time Turns to Sand',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/0444bc247372103.69d920e1524f2.jpg',
                'slug'           => 'namib--where-time-turns-to-sand-344daa9e',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'House of the Dragon Sigil Style Guide',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/cf2479201298395.667200733b67c.png',
                'slug'           => 'house-of-the-dragon-sigil-style-guide-1cd11867',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Logofolio 6',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/775db7248084861.69e9d8a55d857.jpg',
                'slug'           => 'logofolio-6-e74f0c06',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'WASARA',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/65ac0f228819529.6862e8fb6392a.png',
                'slug'           => 'wasara-d7ddf587',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Comics',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/hd/739975247993409.69e79466e3645.png',
                'slug'           => 'comics-7ba36faf',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Porsche Turbo S 992.2',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/06d3ad247237987.69d664c9048de.jpg',
                'slug'           => 'porsche-turbo-s-9922-05a60a9a',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Poster designs IV',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/b2aeb6247978943.69e75b4eaf711.png',
                'slug'           => 'poster-designs-iv-2c0f5542',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'La Deseada',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/03fc74180444857.657a4dd65c72d.jpg',
                'slug'           => 'la-deseada-36fb5625',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Zara Athleticz',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5e295c246259139.69c0ee0011189.jpg',
                'slug'           => 'zara-athleticz-205fd24e',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Russian Drift Series MRW',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/eb1e8f170392405.645cf04b4d3f7.jpg',
                'slug'           => 'russian-drift-series-mrw-cf2c68a3',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Ay Le Le - Lyric Video',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/b7d82f235755107.68f4ce8b99dd5.png',
                'slug'           => 'ay-le-le--lyric-video-326fa0ca',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Studio Namma - Website',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e35644247310965.69dafa2e5dbba.jpg',
                'slug'           => 'studio-namma--website-70ac0b65',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Raulane: A Living Ritual from Kinnaur, Himachal Pradesh',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/3e8a8f247573759.69de3ad7bf495.jpg',
                'slug'           => 'raulane-a-living-ritual-from-kinnaur-himachal-pradesh-2238c711',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => '2D Heads II',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/65ebf9231085161.69e6687d8e4e0.jpg',
                'slug'           => '2d-heads-ii-dbe47a48',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'MCLAREN ARTURA - Seoul Photoshoot',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/4e7403247220153.69d622990c305.jpg',
                'slug'           => 'mclaren-artura--seoul-photoshoot-44cf8b2f',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'BLOSSOM 52',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/a9ef6f247792871.69e29e95f100d.jpg',
                'slug'           => 'blossom-52-2ff4c60e',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Idle Rhythm Action RPG',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/projects/max_808/aa2298240892391.Y3JvcCwxNzAwLDEzMjksMCww.png',
                'slug'           => 'idle-rhythm-action-rpg-7bdd08b0',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Hauswell®. Packaging for a mop',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/5b7e0e244149627.6990dffd2c6f9.jpg',
                'slug'           => 'hauswell-packaging-for-a-mop-4bb229bf',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Yerevanyan | Postcard Series',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/2d6a0a242333261.696a92a05b0de.png',
                'slug'           => 'yerevanyan--postcard-series-ebaf85b7',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Hang Seng Bank Red Packets 2026',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/c6336e248149801.69ea9fb0b8a46.jpg',
                'slug'           => 'hang-seng-bank-red-packets-2026-a6567d9d',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Transferly',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/d17203247098797.69d3bb65e29ad.jpg',
                'slug'           => 'transferly-c3c67c74',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'R3© Clothes Marketplace',
                'description'    => null,
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e07268247093223.69d3a53478e52.png',
                'slug'           => 'r3-clothes-marketplace-cf5e1581',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'user_id'        => 0,
                'title'          => 'Senso — Designing a Better Skincare Tracking Experience',
                'description'    => 'Advanced analytics, your own customized portfolio website, and more features to grow your creative career.',
                'cover_image'    => 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/e9d95c247910197.69e604d14142c.png',
                'slug'           => 'senso--designing-a-better-skincare-tracking-experience-ec9f4f06',
                'status'         => 'published',
                'views_count'    => 0,
                'likes_count'    => 0,
                'comments_count' => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        // Insert dalam chunk 100 supaya tidak timeout
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('projects')->insert($chunk);
        }
    }
}
